name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y check pkg-config

      - name: Configure CMake
        run: cmake -S . -B build_dir -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build_dir -- -j

      - name: Run tests
        run: ctest --test-dir build_dir --output-on-failure
